apiVersion: v1
kind: ConfigMap
metadata: 
  name: msvc-usuarios
data:
  lb_auth_issuer_uri: http://127.0.0.1.9000
  lb_usuarios_uri: http://127.0.0.1.8001
  port: "8001"
  db_host: mysql8:3306
  database: msvc_usuarios
#  db_username: root
#  db_password: root
  cursos_url: msvc-cursos:8002
  application.yaml: |-
    config:
      texto: Configurando ambiente por defecto
    ---
    spring:
      config:
        activated
          on-profile: dev
    config:
      texto: Configurando ambiente de desarrollo
    ---
    spring:
      config:
        activated
          on-profile: prod
    config:
      texto: Configurando ambiente de produccion
    

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc_cursos
data:
  port: "8002"
  db_host: postgres14:5432
  database: msvc_cursos
#  db_username: postgres
#  db_password: root
  usuarios_url: msvc-usuarios:8001