apiVersion: v1
kind: ConfigMap
metadata: 
  name: msvc-usuarios
data:
  port: "8001"
  db_host: mysql8:3306
  database: msvc_usuarios
  db_username: root
  db_password: root
  cursos_url: msvc-cursos:8002

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc_cursos
data:
  port: "8002"
  db_host: postgres14:5432
  database: msvc_cursos
  db_username: postgres
  db_password: root
  usuarios_url: msvc-usuarios:8001