apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  volumeName: mysql-pv
  accessMode:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi