apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessMode:
    - ReadWriteOnce
  hostPath: 
    path: /var/lib/mysql
    type: DirectoryOrCreate