apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  volumeName: postgres-pv
  accessMode:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi