apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessMode:
    - ReadWriteOnce
  hostPath: 
    path: /var/lib/postgresql/data
    type: DirectoryOrCreate